name: CI

on:
  push:
    branches:
      - "**"      
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'CI start')
    runs-on: ubuntu-latest
    env:
      DENO_INSTALL: "${{ env.HOME }}/.deno"
      PATH: "${{ env.HOME }}/.deno/bin:${{ env.PATH }}"
    steps:      
    - uses: actions/checkout@v1
    - name: Install Deno
      run: |
        DENO_VERSION=$(cat .denov)
        curl -fsSL https://deno.land/x/install/install.sh | bash -s -- ${DENO_VERSION}
    - name: Run Tests
      run: |
        deno test -A
    - name: Check Site
      run: |
        deno -A ./tools/fetch_dir.ts ./site
