name: CI

on:
  push:
    branches:
      - "**"      
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'CI start')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Deno
      run: |
        echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV
    - uses: denolib/setup-deno@master
      with:
        deno-version: ${{ env.DENO_VERSION }}
    - name: Fmt check
      run: deno fmt --check
    - name: Check mod.ts
      run: |
        make mod.ts
        git diff --exit-code
    - name: Check license
      run: deno run --allow-read tools/license_checker.ts
    - name: Run Tests
      run: |
        make test
    - name: Check Site
      run: |
        deno run -A ./tools/fetch_dir.ts ./site