name: Bump

on:
  push:
    branches:
       - ci-test
  schedule:
    - cron: 0 13 * * *    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: keroxp/dink-bot@v0.3.3
      with:
        github-repository: ${{ github.repository }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
